FROM golang:1.24.3-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o api

FROM debian:bookworm-slim

RUN useradd -m appuser

COPY --from=builder /app/api /usr/local/bin/api

USER appuser

EXPOSE 8080

ENTRYPOINT ["api"]
